DELIMITER $$

DROP TRIGGER /*!50032 IF EXISTS */ `HEROD-ORDER`.`ZRH_GOODS_CATEGORY_INSERT`$$

CREATE TRIGGER `HEROD-ORDER`.`ZRH_GOODS_CATEGORY_INSERT` AFTER INSERT ON `HEROD-ORDER`.`ZRH_GOODS_CATEGORY`
FOR EACH ROW BEGIN
UPDATE ZRH_SHOP C SET C.TIMESTAMP = NOW() WHERE C.ID = NEW.SHOP_ID;
END$$

DROP TRIGGER /*!50032 IF EXISTS */ `HEROD-ORDER`.`ZRH_GOODS_CATEGORY_UPDATE`$$

CREATE TRIGGER `HEROD-ORDER`.`ZRH_GOODS_CATEGORY_UPDATE` AFTER UPDATE ON `HEROD-ORDER`.`ZRH_GOODS_CATEGORY`
FOR EACH ROW BEGIN
UPDATE ZRH_SHOP C SET C.TIMESTAMP = NOW() WHERE C.ID = OLD.SHOP_ID;
END$$

DROP TRIGGER /*!50032 IF EXISTS */ `HEROD-ORDER`.`ZRH_GOODS_CATEGORY_DELETE`$$

CREATE TRIGGER `HEROD-ORDER`.`ZRH_GOODS_CATEGORY_DELETE` AFTER DELETE ON `HEROD-ORDER`.`ZRH_GOODS_CATEGORY`
FOR EACH ROW BEGIN
UPDATE ZRH_SHOP C SET C.TIMESTAMP = NOW() WHERE C.ID = OLD.SHOP_ID;
END$$

DELIMITER ;