DELIMITER $$

DROP TRIGGER /*!50032 IF EXISTS */ `HEROD-ORDER`.`ZRH_GOODS_INSERT`$$

CREATE TRIGGER `HEROD-ORDER`.`ZRH_GOODS_INSERT` AFTER INSERT ON `HEROD-ORDER`.`ZRH_GOODS`
FOR EACH ROW BEGIN
UPDATE ZRH_GOODS_CATEGORY C SET C.TIMESTAMP = NOW() WHERE C.ID = NEW.CATEGORY_ID;
END$$

DROP TRIGGER /*!50032 IF EXISTS */ `HEROD-ORDER`.`ZRH_GOODS_UPDATE`$$

CREATE TRIGGER `HEROD-ORDER`.`ZRH_GOODS_UPDATE` AFTER UPDATE ON `HEROD-ORDER`.`ZRH_GOODS`
FOR EACH ROW BEGIN
UPDATE ZRH_GOODS_CATEGORY C SET C.TIMESTAMP = NOW() WHERE C.ID = OLD.CATEGORY_ID;
END$$

DROP TRIGGER /*!50032 IF EXISTS */ `HEROD-ORDER`.`ZRH_GOODS_DELETE`$$

CREATE TRIGGER `HEROD-ORDER`.`ZRH_GOODS_DELETE` AFTER DELETE ON `HEROD-ORDER`.`ZRH_GOODS`
FOR EACH ROW BEGIN
UPDATE ZRH_GOODS_CATEGORY C SET C.TIMESTAMP = NOW() WHERE C.ID = OLD.CATEGORY_ID;
END$$

DELIMITER ;