CREATE TRIGGER `ZRH_SHOP_INSERT` AFTER INSERT ON `ZRH_SHOP`
FOR EACH ROW BEGIN UPDATE ZRH_SHOP_TYPE C SET C.TIMESTAMP = NOW() WHERE C.ID = NEW.SHOP_TYPE_ID; END;

CREATE TRIGGER `ZRH_SHOP_UPDATE` AFTER UPDATE ON `ZRH_SHOP`
FOR EACH ROW BEGIN UPDATE ZRH_SHOP_TYPE C SET C.TIMESTAMP = NOW() WHERE C.ID = OLD.SHOP_TYPE_ID; END;

CREATE TRIGGER `ZRH_SHOP_DELETE` AFTER DELETE ON `ZRH_SHOP`
FOR EACH ROW BEGIN UPDATE ZRH_SHOP_TYPE C SET C.TIMESTAMP = NOW() WHERE C.ID = OLD.SHOP_TYPE_ID; END;

CREATE TRIGGER `ZRH_GOODS_CATEGORY_INSERT` AFTER INSERT ON `ZRH_GOODS_CATEGORY`
FOR EACH ROW BEGIN UPDATE ZRH_SHOP C SET C.TIMESTAMP = NOW() WHERE C.ID = NEW.SHOP_ID; END;

CREATE TRIGGER `ZRH_GOODS_CATEGORY_UPDATE` AFTER UPDATE ON `ZRH_GOODS_CATEGORY`
FOR EACH ROW BEGIN UPDATE ZRH_SHOP C SET C.TIMESTAMP = NOW() WHERE C.ID = OLD.SHOP_ID; END;

CREATE TRIGGER `ZRH_GOODS_CATEGORY_DELETE` AFTER DELETE ON `ZRH_GOODS_CATEGORY`
FOR EACH ROW BEGIN UPDATE ZRH_SHOP C SET C.TIMESTAMP = NOW() WHERE C.ID = OLD.SHOP_ID; END;


CREATE TRIGGER `ZRH_GOODS_INSERT` AFTER INSERT ON `ZRH_GOODS`
FOR EACH ROW BEGIN UPDATE ZRH_GOODS_CATEGORY C SET C.TIMESTAMP = NOW() WHERE C.ID = NEW.CATEGORY_ID; END;

CREATE TRIGGER `ZRH_GOODS_UPDATE` AFTER UPDATE ON `ZRH_GOODS`
FOR EACH ROW BEGIN UPDATE ZRH_GOODS_CATEGORY C SET C.TIMESTAMP = NOW() WHERE C.ID = OLD.CATEGORY_ID; END;

CREATE TRIGGER `ZRH_GOODS_DELETE` AFTER DELETE ON `ZRH_GOODS`
FOR EACH ROW BEGIN UPDATE ZRH_GOODS_CATEGORY C SET C.TIMESTAMP = NOW() WHERE C.ID = OLD.CATEGORY_ID; END;

