ALTER TABLE ZRH_AGENT ADD COLUMN  DELETE_FLAG TINYINT(1) DEFAULT '0';
ALTER TABLE ZRH_AGENT_DELIVERY_WORKER ADD COLUMN  DELETE_FLAG TINYINT(1) DEFAULT '0';
ALTER TABLE ZRH_GOODS ADD COLUMN  DELETE_FLAG TINYINT(1) DEFAULT '0';
ALTER TABLE ZRH_GOODS_CATEGORY ADD COLUMN  DELETE_FLAG TINYINT(1) DEFAULT '0';
ALTER TABLE ZRH_ORDER ADD COLUMN  DELETE_FLAG TINYINT(1) DEFAULT '0';
ALTER TABLE ZRH_ORDER_ITEM ADD COLUMN  DELETE_FLAG TINYINT(1) DEFAULT '0';
ALTER TABLE ZRH_ORDER_LOG ADD COLUMN  DELETE_FLAG TINYINT(1) DEFAULT '0';
ALTER TABLE ZRH_SHOP ADD COLUMN  DELETE_FLAG TINYINT(1) DEFAULT '0';
ALTER TABLE ZRH_SHOP_TYPE ADD COLUMN  DELETE_FLAG TINYINT(1) DEFAULT '0';

update  `COMPONENT` set `FUNCCLASS` = 'grid.InfoManagerGridPanel' 
where `ID` in (10001,10002,10003,10004,10006,10007,10008);

update `MENU` set `FUNCCLASS` = 'grid.InfoManagerGridPanel' 
where `ID` in (10001,10002,10008,10009);

update `DATA_SET` set `_SQL` = 'SELECT ID, NAME FROM ZRH_SHOP_TYPE WHERE DELETE_FLAG = 0' where `CODE` = 'SHOP_TYPE_VIEW';
update `DATA_SET` set `_SQL` = 'SELECT S.ID, S.NAME, T.NAME SHOP_TYPE_NAME, S.ADDRESS, S.CONTACT_NUMBER, S.AGENT_ID FROM ZRH_SHOP S LEFT JOIN ZRH_SHOP_TYPE T ON S.SHOP_TYPE_ID = T.ID WHERE S.DELETE_FLAG = 0' where `CODE` = 'SHOP_VIEW';